apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "true"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operatorframework.io/suggested-namespace: openstack
    operators.openshift.io/infrastructure-features: '["disconnected"]'
    operators.operatorframework.io/operator-type: non-standalone
  name: octavia-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - displayName: Octavia Amphora Controller
      kind: OctaviaAmphoraController
      name: octaviaamphoracontrollers.octavia.openstack.org
      version: v1beta1
    - description: OctaviaAPI is the Schema for the octaviaapis API
      displayName: Octavia API
      kind: OctaviaAPI
      name: octaviaapis.octavia.openstack.org
      specDescriptors:
      - description: TLS - Parameters related to the TLS
        displayName: TLS
        path: tls
      - description: API tls type which encapsulates for API services
        displayName: API
        path: tls.api
      - description: Ovn GenericService - holds the secret for the OvnDb client cert
        displayName: Ovn
        path: tls.ovn
      version: v1beta1
    - description: Octavia is the Schema for the octavia API
      displayName: Octavia
      kind: Octavia
      name: octavias.octavia.openstack.org
      specDescriptors:
      - description: TLS - Parameters related to the TLS
        displayName: TLS
        path: octaviaAPI.tls
      - description: API tls type which encapsulates for API services
        displayName: API
        path: octaviaAPI.tls.api
      - description: Ovn GenericService - holds the secret for the OvnDb client cert
        displayName: Ovn
        path: octaviaAPI.tls.ovn
      - description: TLS - Parameters related to the TLS
        displayName: TLS
        path: octaviaHealthManager.tls
      - description: TLS - Parameters related to the TLS
        displayName: TLS
        path: octaviaHousekeeping.tls
      - description: TLS - Parameters related to the TLS
        displayName: TLS
        path: octaviaWorker.tls
      version: v1beta1
  description: Octavia Operator
  displayName: Octavia Operator
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - OpenStack
  - Load-Balancer
  - Octavia
  links:
  - name: Octavia Operator
    url: https://github.com/openstack-k8s-operators/octavia-operator
  maturity: beta
  provider:
    name: Red Hat Inc.
    url: https://redhat.com/
  version: 0.0.0
